# Generated by Django 2.1.7 on 2019-04-07 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Oximetría', 'OXI'), ('Electrocardiograma', 'ECG'), ('Electrodérmica', 'EDM'), ('Fonocardiograma', 'FNC'), ('Electromiograma', 'EMG')], max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('muestras', models.IntegerField(default=0)),
            ],
        ),
    ]
