# Generated by Django 2.1.7 on 2019-04-07 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Oximetría', 'OXI'), ('Electrodérmica', 'EDM'), ('Electrocardiograma', 'ECG'), ('Fonocardiograma', 'FNC'), ('Electromiograma', 'EMG')], max_length=50),
        ),
    ]
