# Generated by Django 2.1.7 on 2019-04-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0002_auto_20190407_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('FNC', 'Fonocardiograma'), ('OXI', 'Oximetría'), ('ECG', 'Electrocardiograma'), ('EDM', 'Electrodérmica'), ('EMG', 'Electromiograma')], max_length=50),
        ),
    ]
