# Generated by Django 2.1.7 on 2019-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0003_auto_20190408_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electrocardiograma', 'Electrocardiograma'), ('Electromiograma', 'Electromiograma'), ('Fonocardiograma', 'Fonocardiograma'), ('Electrodérmica', 'Electrodérmica'), ('Oximetría', 'Oximetría')], max_length=50),
        ),
    ]
