# Generated by Django 2.1.7 on 2019-04-16 01:30

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0004_auto_20190409_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='data',
            field=picklefield.fields.PickledObjectField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electrocardiograma', 'Electrocardiograma'), ('Electromiograma', 'Electromiograma'), ('Electrodérmica', 'Electrodérmica'), ('Fonocardiograma', 'Fonocardiograma'), ('Oximetría', 'Oximetría')], max_length=50),
        ),
    ]
