# Generated by Django 2.1.7 on 2019-05-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0006_auto_20190506_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Fonocardiograma', 'Fonocardiograma'), ('Electromiograma', 'Electromiograma'), ('Oximetría', 'Oximetría'), ('Electrodérmica', 'Electrodérmica'), ('Electrocardiograma', 'Electrocardiograma')], max_length=50),
        ),
        migrations.AddField(
            model_name='descripcion',
            name='senal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecg.Signal'),
        ),
    ]
