# Generated by Django 2.1.7 on 2019-07-19 03:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecg', '0007_auto_20190506_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electromiograma', 'Electromiograma'), ('Electrocardiograma', 'Electrocardiograma'), ('Fonocardiograma', 'Fonocardiograma'), ('Oximetría', 'Oximetría'), ('Electrodérmica', 'Electrodérmica')], max_length=50),
        ),
    ]
