# Generated by Django 2.1.7 on 2019-07-21 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecg', '0008_auto_20190718_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecg.Experimento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Oximetría', 'Oximetría'), ('Electromiograma', 'Electromiograma'), ('Electrodérmica', 'Electrodérmica'), ('Electrocardiograma', 'Electrocardiograma'), ('Fonocardiograma', 'Fonocardiograma')], max_length=50),
        ),
    ]
