# Generated by Django 2.1.7 on 2019-07-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0009_auto_20190721_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboracion',
            old_name='usuario',
            new_name='colaborador',
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Fonocardiograma', 'Fonocardiograma'), ('Electromiograma', 'Electromiograma'), ('Oximetría', 'Oximetría'), ('Electrocardiograma', 'Electrocardiograma'), ('Electrodérmica', 'Electrodérmica')], max_length=50),
        ),
    ]
