# Generated by Django 2.1.7 on 2019-07-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0010_auto_20190721_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='experimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecg.Experimento'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Fonocardiograma', 'Fonocardiograma'), ('Electrodérmica', 'Electrodérmica'), ('Electromiograma', 'Electromiograma'), ('Oximetría', 'Oximetría'), ('Electrocardiograma', 'Electrocardiograma')], max_length=50),
        ),
    ]
