# Generated by Django 2.1.7 on 2019-07-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0011_auto_20190728_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='detalle',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electrocardiograma', 'Electrocardiograma'), ('Fonocardiograma', 'Fonocardiograma'), ('Electromiograma', 'Electromiograma'), ('Oximetría', 'Oximetría'), ('Electrodérmica', 'Electrodérmica')], max_length=50),
        ),
    ]
