# Generated by Django 2.2.4 on 2019-08-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0012_auto_20190728_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Oximetría', 'Oximetría'), ('Electrodérmica', 'Electrodérmica'), ('Electromiograma', 'Electromiograma'), ('Electrocardiograma', 'Electrocardiograma'), ('Fonocardiograma', 'Fonocardiograma')], max_length=50),
        ),
    ]
