# Generated by Django 2.1.7 on 2019-11-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0013_auto_20190824_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electrodérmica', 'Electrodérmica'), ('Oximetría', 'Oximetría'), ('Electromiograma', 'Electromiograma'), ('Electrocardiograma', 'Electrocardiograma'), ('Fonocardiograma', 'Fonocardiograma')], max_length=50),
        ),
    ]
