# Generated by Django 2.1.7 on 2019-12-05 23:07

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0014_auto_20191125_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestras', models.IntegerField(default=0)),
                ('data', picklefield.fields.PickledObjectField(default=0, editable=False)),
                ('frecuencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electromiograma', 'Electromiograma'), ('Electrocardiograma', 'Electrocardiograma'), ('Electrodérmica', 'Electrodérmica'), ('Fonocardiograma', 'Fonocardiograma'), ('Oximetría', 'Oximetría')], max_length=50),
        ),
        migrations.AddField(
            model_name='senaldata',
            name='senal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecg.Signal'),
        ),
    ]
