# Generated by Django 2.1.7 on 2019-12-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0015_auto_20191205_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Fonocardiograma', 'Fonocardiograma'), ('Oximetría', 'Oximetría'), ('Electrodérmica', 'Electrodérmica'), ('Electromiograma', 'Electromiograma'), ('Electrocardiograma', 'Electrocardiograma')], max_length=50),
        ),
    ]
