# Generated by Django 2.1.7 on 2019-12-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0016_auto_20191205_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SenalData',
            new_name='Datasenal',
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electrocardiograma', 'Electrocardiograma'), ('Electrodérmica', 'Electrodérmica'), ('Electromiograma', 'Electromiograma'), ('Fonocardiograma', 'Fonocardiograma'), ('Oximetría', 'Oximetría')], max_length=50),
        ),
    ]
