# Generated by Django 2.1.7 on 2019-12-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0019_auto_20191207_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Oximetría', 'Oximetría'), ('Electrodérmica', 'Electrodérmica'), ('Electromiograma', 'Electromiograma'), ('Electrocardiograma', 'Electrocardiograma'), ('Fonocardiograma', 'Fonocardiograma')], max_length=50),
        ),
    ]
