# Generated by Django 2.2.4 on 2019-12-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0020_auto_20191213_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Oximetría', 'Oximetría'), ('Electrocardiograma', 'Electrocardiograma'), ('Fonocardiograma', 'Fonocardiograma'), ('Electrodérmica', 'Electrodérmica'), ('Electromiograma', 'Electromiograma')], max_length=50),
        ),
    ]
