# Generated by Django 2.1.7 on 2019-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0021_auto_20191213_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electrocardiograma', 'Electrocardiograma'), ('Oximetría', 'Oximetría'), ('Fonocardiograma', 'Fonocardiograma'), ('Electromiograma', 'Electromiograma'), ('Electrodérmica', 'Electrodérmica')], max_length=50),
        ),
    ]
