# Generated by Django 2.1.7 on 2019-12-26 04:14

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0022_auto_20191215_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcionecg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtrada', picklefield.fields.PickledObjectField(default=0, editable=False)),
                ('hrv', picklefield.fields.PickledObjectField(default=0, editable=False)),
                ('bpm', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='signal',
            name='categoria',
            field=models.CharField(choices=[('Electromiograma', 'Electromiograma'), ('Oximetría', 'Oximetría'), ('Electrocardiograma', 'Electrocardiograma'), ('Fonocardiograma', 'Fonocardiograma'), ('Electrodérmica', 'Electrodérmica')], max_length=50),
        ),
        migrations.AddField(
            model_name='descripcionecg',
            name='senal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecg.Signal'),
        ),
    ]
